### PR TITLE
Update terms

### PR DESCRIPTION
**Pull request by johanlives**
New ToS, 2.13

### CODE REVIEW

**Comment by Erwyn** [comment]
@johanlives would you care to explain? Why would bountysource keep the money instead of handing it back to the initial backer(s) ?

**Comment by johanlives** [comment]
> @johanlives would you care to explain? Why would bountysource keep the money instead of handing it back to the initial backer(s) ?

Hi @Erwyn 
This is a change that the Bountysource stakeholders have requested after legal preparation.
I believe it's part of developing plans to fix Bountysource's systemic site issues, re-engineer the legacy codebase & systems and clean-up the issues & userbase.  As part of this, a recent analysis identified many aged accounts & bounties.  

From what I understand, initial backers will be contacted but in the event of lapsed details or orphaned accounts, these new ToS provide a legal/accounting framework for Bountysource to re-allocate funds.

Note:  I am not a stakeholder, in an executive position or qualified on legal matters. This is simply my answer based on what I currently understand from internal communications and questions I've raised myself.

**Comment by dreua** [comment]
> From what I understand, initial backers will be contacted but in the event of lapsed details or orphaned accounts, these new ToS provide a legal/accounting framework for Bountysource to re-allocate funds.

Well than this should be *in* the ToS so that it can not silently be *forgotten*. Also it written that this option to reallocate only applies to bounties posted "before June 30, 2018", i.e. all other bounties and those posted in the future can not be reallocated or refunded? Can we have some data on how much money this is VS how much actually gets paid to open source developers?

> Note: I am not a stakeholder, in an executive position or qualified on legal matters. This is simply my answer based on what I currently understand from internal communications and questions I've raised myself.

I totally understand and feel sorry for you being in this position right now. Could you give us a way to directly contact those "stakeholders" so we can <strike>route the shitstorm</strike> send questions and comments directly to them?

**Comment by Phoenix616** [comment]
Please remove this change and implement a way to just return the money to the sender like all major other bounty platforms like [gitcoin.co](https://gitcoin.co) or [issuehunt.io](https://issuehunt.io) do it. They keep the transaction/service fees though but that is kinda reasonable, keeping all of the money is not. There are large bounties on your platform that are older than two years...

So please ensure that all money of bounties from before this change is at least handled separately and an indefinite way of moving the money to other bounties is possible until a way for withdrawing/automatic returnal of these bounties is implemented.

**Comment by aikar** [comment]
Did you not consider the PR impact such a change would have and how devastating it could be to your service?

Why would a backer want to use a service that puts an artificial time limit on their bounty?

**Comment by johanlives** [comment]
@dreua @Phoenix616 @aikar 

New ToS to be withdrawn.  Stay tuned.

Thankyou for directing your outrage at the decision makers and not me personally.

**Pull request merged**
