### PR TITLE
fix: Fix find method call in API's timeline_controller affecting query of issue event history

### PR DESCRIPTION
**Pull request by brymut**
fix https://github.com/bountysource/core/issues/1445
changes made:
Changed parameter for `find(` method call affecting the API call used in front end to populate issue event history.

### CODE REVIEW

**Comment by brymut** [comment]
Hi @johanlives , sorry to ping if you're busy, may I please have someone look at this?

**Comment by johanlives** [comment]
Hi @brymut 
Thanks, we'll attend this shortly

**Comment by brymut** [comment]
Hi again, is there any update on this?

**Comment by johanlives** [comment]
> Hi again, is there any update on this?

Hi @brymut 
If you're interested in helping with other issues, please send me a email at support@bountysource.com.

**Comment by brymut** [comment]
Hi @johanlives, I am interested in helping out with other issues, I've just sent one out.

**Pull request merged**
