### PR TITLE
Revert "fix: currency filter issue causing $NaN in receipt"

### PR DESCRIPTION
**Pull request by johanlives**
Reverts bountysource/core#1476

### CODE REVIEW

**Comment by brymut** [comment]
Hi @johanlives, why was this reverted?

**Comment by johanlives** [comment]
> Hi @johanlives, why was this reverted?

Hey @brymut 
The app crashed as soon as I deployed. Naturally, I quickly reverted.
But it didn't fix the issue.   I think the deploy was a red herring.
We're still trying to resolve the issue.
Getting a stack of H10, H20 & R10 heroku issues.
Once we can get the site stable again, we'll get back to your merge.

Side note:  We will also get back to your other PR and if all good, I will retroactively put a bounty on it for you.

**Comment by brymut** [comment]
oh damn, alright, no problem. Thanks for getting back to me, I'll hold on.

**Comment by johanlives** [comment]
> oh damn, alright, no problem. Thanks for getting back to me @johanlives, I'll hold on.

Damn alright ;)  We are chasing errors at the moment unfortunately and it's not good for user experience

**Comment by brymut** [comment]
Well, I'm willing to help whichever way possible. Hopefully things get sorted and get better soon, must be stressful.

**Comment by johanlives** [comment]
@brymut 
Can you push again

**Comment by brymut** [comment]
@johanlives created new pull request.

**Pull request merged**
