### PR TITLE
Do not add Bitcoin to the money registry

### PR DESCRIPTION
**Pull request by KrzysiekJ**
While Bitcoin is added to the money registry, Ripple and Mastercoin are not. Also stopping adding Bitcoin to the registry doesn’t cause any test to fail. Therefore my hypothesis is that this code is unnecessary.

By the way: Bitcoin’s (unofficial) ISO code is XBT and the satoshi unit is written lowercase.

### CODE REVIEW

**Comment by 3rdwiki** [comment]
I don't understand what this is for ?

Is this to finish with _ALL_ BTC transactions all together ?

**Comment by iHateInventNames** [comment]
I do not understand either, why? Could you, please, provide some rationale, @KrzysiekJ?

**Comment by KrzysiekJ** [comment]
Removing this code doesn’t seem to change anything, Money registry isn’t used in Bountysource (at least for cryptocurrencies). Therefore this is in some sense dead code and keeping it in the repository may be misleading. Bitcoin should be still fully functional after merging this pull request.

**Comment by NoNonsense126** [comment]
Thanks for the PR, but we'll be revamping our payment methods going forward. We'll remove it if needed in the future.

**Pull request closed without merging**
